# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-16 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_added',),
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='trips', max_length=250, unique_for_date='date_added')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('detail', models.TextField()),
                ('start', models.DateField(blank=True)),
                ('End', models.DateField(blank=True)),
                ('summary', models.TextField()),
                ('included', models.TextField()),
                ('excluded', models.TextField()),
                ('availability', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=50)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='trips')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.Category')),
            ],
            options={
                'ordering': ('-date_added',),
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.Trip'),
        ),
    ]
