# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 10:39
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('tour', '0003_auto_20190716_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
