# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2022-04-28 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premise', '0004_auto_20220428_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'ServiceCategories'},
        ),
    ]
