# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2022-04-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premise', '0005_auto_20220428_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
