"""
Django settings for my_apps project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'apps.settings'
from django.core.urlresolvers import reverse_lazy
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_DIR = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'whenindarkletyourheartshowyoutheway'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'address',
    'college.apps.CollegeConfig',
    'django.contrib.auth',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'premise.apps.PremiseConfig',
    'finders.apps.FindersConfig',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'home.apps.HomeConfig',
    'events.apps.EventsConfig',
    'student.apps.StudentConfig',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'memcache_status',
    'tour.apps.TourConfig',
    'taggit',
    'places',
    'dal',
    'dal_select2',
    'dal_legacy_static',
    'phonenumber_field',
    'django_ajax',
    'smart_selects',

    ]
MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 60 * 15  # 15 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'college'


ROOT_URLCONF = 'apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
         'libraries': {
              'events_tags': 'events.templatetags.events_tags',
              'testi_tags': 'home.templatetags.testi_tags',
              'display_tags': 'home.templatetags.display_tags',
              'trips_tags': 'tour.templatetags.trips_tags',
              'wildlife_tags': 'tour.templatetags.wildlife_tags',
              'weekend_tags': 'tour.templatetags.weekend_tags',
              'roadtrips': 'tour.templatetags.roadtrips',
              'holiday_tags': 'tour.templatetags.holiday_tags',
              'news_tag': 'home.templatetags.news_tag',
              'politics_tag': 'home.templatetags.politics_tag',
              'sports_tag': 'home.templatetags.sports_tag',
              'opinions': 'home.templatetags.opinions',
              'videos_tag': 'home.templatetags.videos_tag',
              'rent_tags': 'premise.templatetags.rent_tags',
              'buy_tags': 'premise.templatetags.buy_tags',
             'shortstay_tags': 'premise.templatetags.shortstay_tags',
             'type_tag': 'premise.templatetags.type_tag',
             'services_tag': 'premise.templatetags.services_tag',
             'templatehelper': 'premise.templatetags.templatehelper',
          },
        },
    },
]
AUTH_USER_MODEL = 'premise.User'
WSGI_APPLICATION = 'apps.wsgi.application'
WAGTAIL_SITE_NAME = 'News and Events'

LOGIN_REDIRECT_URL = reverse_lazy('finders:common')
LOGIN_URL = reverse_lazy('login')
LOGOUT_URL = reverse_lazy('logout')
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':
            'django.db.backends.sqlite3',
        'NAME': 'platiabase',
        'USER': 'admin',
        'PASSWORD': '',
        'HOST': 'localhost',

    }
}
CACHES = {
    'default': {
     'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
     'LOCATION': '127.0.0.1:11211',
     }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
PLACES_MAPS_API_KEY = 'YourAwesomeUltraSecretKey'
PLACES_MAP_WIDGET_HEIGHT = 480
PLACES_MAP_OPTIONS = '{"center": { "lat": 38.971584, "lng": -95.235072 }, "zoom": 10}'
PLACES_MARKER_OPTIONS = '{"draggable": true}'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIR = (BASE_DIR, 'static')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    #'django.contrib.staticfiles.finders.DefaultStorageFinder',
]

GOOGLE_API_KEY = 'jjjj'
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'platiafinder@gmail.com'
EMAIL_HOST_PASSWORD = '100404??'



